CC=g++
CFLAGS=-c -Wall
LDFLAGS=

SERVER_SOURCES= ServerMain.cpp Server.cpp SocketAdapter.cpp
SERVER_OBJECTS=$(SERVER_SOURCES:.cpp=.o)
SERVER_EXECUTABLE=server
CLIENT_SOURCES= ClientMain.cpp Client.cpp SocketAdapter.cpp
CLIENT_OBJECTS=$(CLIENT_SOURCES:.cpp=.o)
CLIENT_EXECUTABLE=client

all: $(CLIENT_SOURCES) $(CLIENT_EXECUTABLE) $(SERVER_EXECUTABLE) $(SERVER_SOURCES)
	
$(SERVER_EXECUTABLE): $(SERVER_OBJECTS) 
	$(CC) $(LDFLAGS) $(SERVER_OBJECTS) -o $@


$(CLIENT_EXECUTABLE): $(CLIENT_OBJECTS) 
	$(CC) $(LDFLAGS) $(CLIENT_OBJECTS) -o $@

.cpp.o:
	$(CC) $(CFLAGS) $< -o $@

clean:
	rm -rf $(CLIENT_OBJECTS) $(SERVER_OBJECTS) $(CLIENT_EXECUTABLE) $(SERVER_EXECUTABLE)